name: ci
on: [push, workflow_dispatch]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:12.20-buster-slim

    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm ruun build

      - name: Test
        run: npm run test -- --runInBand
        env:
          REDIS_HOST: redis
          REDIS_PORT: 6379

      - name: Publish
        uses: pascalgn/npm-publish-action@1.3.6
        with: # All of theses inputs are optional
          tag_name: "v%s"
          tag_message: "v%s"
          create_tag: "true"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
          publish_command: "yarn"
          publish_args: "--non-interactive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this as is, it's automatically generated
          NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}